services:
  frontend-portal-server:
    image: ghcr.io/forepath/agenstra-portal-server:latest
    container_name: portal-server
    environment:
      # Frontend server configuration
      HOST: 0.0.0.0
      PORT: 4200
      NODE_ENV: production
      DEFAULT_LOCALE: en
    ports:
      - '4200:4200'
    networks:
      - portal-network
    restart: unless-stopped

networks:
  portal-network:
    driver: bridge
